export const ERROR_CODES = {
  LESSON_LOCKED: 'LESSON_LOCKED',
  BLOCKED_WARNING: 'BLOCKED_WARNING',
  BLOCKED_PAYMENT: 'BLOCKED_PAYMENT',
  DELEGATION_EXPIRED: 'DELEGATION_EXPIRED',
  DELEGATION_NOT_PENDING: 'DELEGATION_NOT_PENDING',
  DELEGATION_PERMISSION_DENIED: 'DELEGATION_PERMISSION_DENIED',
  PAYMENT_ALREADY_MARKED: 'PAYMENT_ALREADY_MARKED',
  ATTENDANCE_ALREADY_RECORDED: 'ATTENDANCE_ALREADY_RECORDED',
  WARNING_LIMIT_EXCEEDED: 'WARNING_LIMIT_EXCEEDED',
  FACE_NOT_RECOGNIZED: 'FACE_NOT_RECOGNIZED',
  FACE_NOT_ENROLLED: 'FACE_NOT_ENROLLED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
